//! Generation of the manifest reference pages from the checked-in JSON Schema.
//!
//! `doc-gen manifest` walks `docs/spec/manifest-v0.schema.json` and emits one
//! markdown page per top-level section and per resource kind under
//! `docs/book/src/reference/manifest/`, plus a page of shared types. The output
//! is checked in and verified fresh by CI, so the reference can never drift
//! from the Rust types it documents.

use std::collections::BTreeSet;
use std::fmt::Write as _;

use anyhow::{Context, Result};
use serde_json::{Map, Value};

use super::{cell, page, write_or_check};

/// Canonical JSON Schema, relative to the workspace root.
const SCHEMA_PATH: &str = "docs/spec/manifest-v0.schema.json";
/// Directory holding the generated manifest reference pages.
const MANIFEST_REF_DIR: &str = "docs/book/src/reference/manifest";
/// Banner stamped at the top of every generated page.
const GENERATED_NOTE: &str =
    "<!-- Generated by `cargo xtask doc-gen manifest`. Do not edit by hand. -->\n\n";

/// Top-level sections rendered as their own page: (file stem, `$defs` name, title).
const SECTIONS: &[(&str, &str, &str)] = &[
    ("project", "Project", "project"),
    ("dashboard", "DashboardConfig", "dashboard"),
    ("observability", "ObservabilityConfig", "observability"),
    ("export", "ExportConfig", "export"),
];

/// Resource kinds rendered as their own page: (file stem / yaml key, `$defs` name, title).
const KINDS: &[(&str, &str, &str)] = &[
    ("postgres", "PostgresConfig", "postgres"),
    ("redis", "RedisConfig", "redis"),
    ("container", "ContainerConfig", "container"),
    ("dockerfile", "DockerfileConfig", "dockerfile"),
];

/// Generate (or verify with `--check`) the manifest reference pages.
pub(super) fn manifest(check: bool) -> Result<()> {
    let raw = std::fs::read_to_string(SCHEMA_PATH)
        .with_context(|| format!("failed to read {SCHEMA_PATH}"))?;
    let schema: Value =
        serde_json::from_str(&raw).with_context(|| format!("failed to parse {SCHEMA_PATH}"))?;
    let defs = schema
        .get("$defs")
        .and_then(Value::as_object)
        .context("schema has no $defs object")?;

    let page_defs: BTreeSet<String> = SECTIONS
        .iter()
        .chain(KINDS)
        .map(|(_, def, _)| (*def).to_owned())
        .collect();
    let shared = discover_shared(defs, &page_defs);

    let link = |name: &str| -> String {
        if let Some((stem, _, _)) = SECTIONS.iter().chain(KINDS).find(|(_, d, _)| *d == name) {
            format!("[{name}]({stem}.md)")
        } else if shared.contains(name) {
            format!("[{name}](common-types.md#{})", anchor(name))
        } else {
            format!("`{name}`")
        }
    };

    let mut pages = vec![page(MANIFEST_REF_DIR, "index.md", render_index())];
    for (stem, def, title) in SECTIONS.iter().chain(KINDS) {
        let body = format!(
            "{GENERATED_NOTE}{}",
            render_type(defs, def, title, 1, &link)
        );
        pages.push(page(MANIFEST_REF_DIR, &format!("{stem}.md"), body));
    }
    pages.push(page(
        MANIFEST_REF_DIR,
        "common-types.md",
        render_common(defs, &shared, &link),
    ));

    write_or_check("manifest", MANIFEST_REF_DIR, &pages, check)
}

/// Transitive closure of `$defs` reachable from the page defs but not themselves
/// a page: these shared sub-types are documented once on `common-types.md`.
fn discover_shared(defs: &Map<String, Value>, page_defs: &BTreeSet<String>) -> BTreeSet<String> {
    let mut shared = BTreeSet::new();
    let mut processed = BTreeSet::new();
    let mut stack: Vec<String> = page_defs.iter().cloned().collect();

    while let Some(name) = stack.pop() {
        if !processed.insert(name.clone()) {
            continue;
        }
        let Some(def) = defs.get(&name) else { continue };
        let mut refs = Vec::new();
        collect_refs(def, &mut refs);
        for r in refs {
            if page_defs.contains(&r) {
                continue;
            }
            if shared.insert(r.clone()) {
                stack.push(r);
            }
        }
    }

    shared
}

/// Collect every `$ref` target name found anywhere within a JSON value.
fn collect_refs(value: &Value, out: &mut Vec<String>) {
    match value {
        Value::Object(map) => {
            for (key, val) in map {
                if key == "$ref" {
                    if let Some(target) = val.as_str() {
                        out.push(ref_name(target).to_owned());
                    }
                } else {
                    collect_refs(val, out);
                }
            }
        }
        Value::Array(items) => {
            for item in items {
                collect_refs(item, out);
            }
        }
        _ => {}
    }
}

/// Render the `common-types.md` page documenting every shared sub-type.
fn render_common(
    defs: &Map<String, Value>,
    shared: &BTreeSet<String>,
    link: &dyn Fn(&str) -> String,
) -> String {
    let mut out = format!(
        "{GENERATED_NOTE}# Common types\n\n\
         Shared configuration types referenced from the manifest sections and \
         resource kinds above.\n\n"
    );
    for name in shared {
        out.push_str(&render_type(defs, name, name, 2, link));
    }
    out
}

/// Render one `$defs/<name>` object as a heading, its description and a field table.
fn render_type(
    defs: &Map<String, Value>,
    name: &str,
    title: &str,
    level: usize,
    link: &dyn Fn(&str) -> String,
) -> String {
    let mut out = format!("{} {title}\n\n", "#".repeat(level));
    let def = defs.get(name);

    if let Some(desc) = def
        .and_then(|d| d.get("description"))
        .and_then(Value::as_str)
    {
        let trimmed = desc.trim();
        if !trimmed.is_empty() {
            out.push_str(trimmed);
            out.push_str("\n\n");
        }
    }

    let required: BTreeSet<&str> = def
        .and_then(|d| d.get("required"))
        .and_then(Value::as_array)
        .map(|a| a.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();

    if let Some(props) = def
        .and_then(|d| d.get("properties"))
        .and_then(Value::as_object)
    {
        out.push_str("| Field | Type | Required | Default | Description |\n");
        out.push_str("| --- | --- | --- | --- | --- |\n");
        for (field, prop) in props {
            let ty = type_label(prop, link);
            let req = if required.contains(field.as_str()) {
                "yes"
            } else {
                "no"
            };
            let default = prop
                .get("default")
                .filter(|d| !d.is_null())
                .map(|d| format!("`{}`", serde_json::to_string(d).unwrap_or_default()))
                .unwrap_or_default();
            let desc = prop
                .get("description")
                .and_then(Value::as_str)
                .map(cell)
                .unwrap_or_default();
            writeln!(out, "| `{field}` | {ty} | {req} | {default} | {desc} |")
                .expect("writing to a String is infallible");
        }
        out.push('\n');
    }

    out
}

/// Resolve a property's schema into a human label, linking referenced `$defs`.
fn type_label(prop: &Value, link: &dyn Fn(&str) -> String) -> String {
    if let Some(reference) = prop.get("$ref").and_then(Value::as_str) {
        return link(ref_name(reference));
    }
    for combinator in ["anyOf", "oneOf"] {
        if let Some(members) = prop.get(combinator).and_then(Value::as_array) {
            let labels: Vec<String> = members
                .iter()
                .filter(|m| m.get("type").and_then(Value::as_str) != Some("null"))
                .map(|m| type_label(m, link))
                .collect();
            if !labels.is_empty() {
                return labels.join(" or ");
            }
        }
    }
    match prop.get("type") {
        Some(Value::String(ty)) => scalar_or_container(ty, prop, link),
        Some(Value::Array(variants)) => variants
            .iter()
            .filter_map(Value::as_str)
            .filter(|t| *t != "null")
            .collect::<Vec<_>>()
            .join(" or "),
        _ => "object".to_owned(),
    }
}

/// Label a scalar type, or recurse into the element type of an array or map.
fn scalar_or_container(ty: &str, prop: &Value, link: &dyn Fn(&str) -> String) -> String {
    match ty {
        "array" => match prop.get("items") {
            Some(items) => format!("array of {}", type_label(items, link)),
            None => "array".to_owned(),
        },
        "object" => match prop.get("additionalProperties") {
            Some(additional) if additional.is_object() => {
                format!("map of {}", type_label(additional, link))
            }
            _ => "object".to_owned(),
        },
        other => other.to_owned(),
    }
}

/// Render the manifest reference landing page.
fn render_index() -> String {
    format!(
        "{GENERATED_NOTE}# Manifest reference\n\n\
         These pages are generated from the JSON Schema \
         (`docs/spec/manifest-v0.schema.json`) by `cargo xtask doc-gen manifest`. \
         Do not edit them by hand.\n\n\
         ## Top-level sections\n\n\
         - [project](project.md) (required)\n\
         - `resources` (required): a map of resource names to one resource kind below\n\
         - [dashboard](dashboard.md)\n\
         - [observability](observability.md)\n\
         - [export](export.md)\n\n\
         ## Resource kinds\n\n\
         Each `resources` entry selects exactly one kind:\n\n\
         - [postgres](postgres.md)\n\
         - [redis](redis.md)\n\
         - [container](container.md)\n\
         - [dockerfile](dockerfile.md)\n\n\
         ## Shared types\n\n\
         - [Common types](common-types.md)\n"
    )
}

/// The final segment of a `#/$defs/Name` reference.
fn ref_name(reference: &str) -> &str {
    reference.rsplit('/').next().unwrap_or(reference)
}

/// The mdBook heading anchor for a shared type on `common-types.md`.
fn anchor(name: &str) -> String {
    name.to_lowercase()
}
