msrv = "1.88"

doc-valid-idents = [
    "..",
    "Encelade",
    "GitHub",
    "Hexeract",
    "IntelliJ",
    "Kafka",
    "Kubernetes",
    "LightShuttle",
    "MySQL",
    "NATS",
    "Nubster",
    "OpenTelemetry",
    "PostgreSQL",
    "RabbitMQ",
    "SQLite",
]
